### ISSUE TITLE
Apply clang-format with LLVM style on C++ source code

### ISSUE THREAD

**Issue by krerkkiat** [OU-CS3560/examples#160]
You can learn about `clang-format` [here](https://clang.llvm.org/docs/ClangFormat.html)

### Tasks
- [ ] Add ` .clang-format` file that specify LLVM as the style at the root of the repository.
- [ ] Apply LLVM style for all source C++ source code file in the repository using `clang-format`
- [ ] For source code that have test cases, run them to make sure that the program is still working properly.

For HW9, this is considered a small PR.
